// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxc0m1G0OkPChH81uTbKB2fQIWWx_4o_g',
    appId: '1:446986083030:web:48c2c6658d2468f9dc8777',
    messagingSenderId: '446986083030',
    projectId: 'zoo-app-d7d27',
    authDomain: 'zoo-app-d7d27.firebaseapp.com',
    storageBucket: 'zoo-app-d7d27.firebasestorage.app',
    measurementId: 'G-FXHKWXRFM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01vqVRLP9cMXoYvkZNQSA6KXBfIM9mT8',
    appId: '1:446986083030:android:8df8ad1c6feaa119dc8777',
    messagingSenderId: '446986083030',
    projectId: 'zoo-app-d7d27',
    storageBucket: 'zoo-app-d7d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzxyuxqxzmc2oX-8Au824dAcm7nolzto',
    appId: '1:446986083030:ios:ebfaf35c2f548ce3dc8777',
    messagingSenderId: '446986083030',
    projectId: 'zoo-app-d7d27',
    storageBucket: 'zoo-app-d7d27.firebasestorage.app',
    iosBundleId: 'com.example.zooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGzxyuxqxzmc2oX-8Au824dAcm7nolzto',
    appId: '1:446986083030:ios:ebfaf35c2f548ce3dc8777',
    messagingSenderId: '446986083030',
    projectId: 'zoo-app-d7d27',
    storageBucket: 'zoo-app-d7d27.firebasestorage.app',
    iosBundleId: 'com.example.zooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxc0m1G0OkPChH81uTbKB2fQIWWx_4o_g',
    appId: '1:446986083030:web:991b78d2767d0090dc8777',
    messagingSenderId: '446986083030',
    projectId: 'zoo-app-d7d27',
    authDomain: 'zoo-app-d7d27.firebaseapp.com',
    storageBucket: 'zoo-app-d7d27.firebasestorage.app',
    measurementId: 'G-ZDZ0MF6T29',
  );
}
